List<Map<String, dynamic>> dummyPlantData = [
  {
    'id': 1,
    'name': 'Spider Plant',
    'type': 'Indoor',
    'waterFrequency': 7,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Partial Shade',
    'img': 'assets/images/Spider Plant.jpeg'
  },
  {
    'id': 2,
    'name': 'Rosemary',
    'type': 'Herb',
    'waterFrequency': 4,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Full Sun',
    'img': 'assets/images/rosemary.jpeg'
  },
  {
    'id': 3,
    'name': 'Lavender',
    'type': 'Outdoor',
    'waterFrequency': 5,
    'fertilizerType': 'Organic',
    'sunlightExposure': 'Full Sun',
    'img': 'assets/images/lavender.jpeg'
  },
  {
    'id': 4,
    'name': 'Daffodils',
    'type': 'Bulb',
    'waterFrequency': 3,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Partial Shade',
    'img': 'assets/images/daffodils.jpeg'
  },
  {
    'id': 5,
    'name': 'Hydrangeas',
    'type': 'Shrub',
    'waterFrequency': 6,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Partial Sun',
    'img': 'assets/images/hydrangea.jpeg'
  },
  {
    'id': 6,
    'name': 'Tulips',
    'type': 'Bulb',
    'waterFrequency': 4,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Full Sun',
    'img': 'assets/images/tulips.jpeg'
  },
  {
    'id': 7,
    'name': 'Roses',
    'type': 'Shrub',
    'waterFrequency': 5,
    'fertilizerType': 'Organic',
    'sunlightExposure': 'Full Sun',
    'img': 'assets/images/roses.jpeg'
  },
  {
    'id': 8,
    'name': 'Peonies',
    'type': 'Perennial',
    'waterFrequency': 6,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Partial Shade',
    'img': 'assets/images/peonis.jpeg'
  },
  {
    'id': 9,
    'name': 'Daylilies',
    'type': 'Perennial',
    'waterFrequency': 4,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Full Sun',
    'img': 'assets/images/day lillies.jpeg'
  },
  {
    'id': 10,
    'name': 'Carnations',
    'type': 'Annual',
    'waterFrequency': 5,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Partial Sun',
    'img': 'assets/images/carnations.jpeg'
  },
  {
    'id': 11,
    'name': 'Basil',
    'type': 'Herb',
    'waterFrequency': 2,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Partial Sun',
    'img':'assets/images/basil.jpeg',
  },
  {
    'id': 12,
    'name': 'Aloe Vera',
    'type': 'Succulent',
    'waterFrequency': 5,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Bright, indirect light',
    'img': 'assets/images/aloe.jpeg',
  },
  {
    'id': 13,
    'name': 'Jade Plant',
    'type': 'Succulent',
    'waterFrequency': 3,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Bright Light',
    'img': 'assets/images/jade.jpeg',
  },
  {
    'id': 14,
    'name': 'Mint',
    'type': 'Herb',
    'waterFrequency': 2,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Partial Sun',
    'img': 'assets/images/mint.jpeg',
  },
  {
    'id': 15,
    'name': 'Orchid',
    'type': 'Flower',
    'waterFrequency': 5,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Indirect Light',
    'img': 'assets/images/orchid.jpeg',
  },
  {
    'id': 16,
    'name': 'Hibiscus',
    'type': 'Flower',
    'waterFrequency': 3,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Full Sun',
    'img': 'assets/images/hibiscus.jpeg',
  },
  {
    'id': 17,
    'name': 'Moss',
    'type': 'Plant',
    'waterFrequency': 4,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Low Light',
    'img': 'assets/images/moss.jpeg',
  },
  {
    'id': 18,
    'name': 'Money Tree',
    'type': 'Tree',
    'waterFrequency': 7,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Bright, indirect light',
    'img': 'assets/images/money tree.jpeg',
  },
  {
    'id': 19,
    'name': 'Pilea Peperomioides',
    'type': 'Houseplant',
    'waterFrequency': 4,
    'fertilizerType': 'Liquid',
    'sunlightExposure': 'Bright, indirect light',
    'img': 'assets/images/pilea.jpeg',
  },
  {
    'id': 20,
    'name': 'ZZ Plant',
    'type': 'Houseplant',
    'waterFrequency': 5,
    'fertilizerType': 'Granular',
    'sunlightExposure': 'Low Light',
    'img': 'assets/images/zz.jpeg',
  },
];
